spring.application.name=api

API_KEY=${API_KEY}

BREVO_API_KEY=${BREVO_API_KEY}

# 1. Output file destination
logging.file.name=logs/User-Actions.log

# 2. File and Console logging patterns with MDC variables
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [Req: %X{requestId} | Sess: %X{sessionId} | User: %X{userId}] %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - [Req: %X{requestId} | Session: %X{sessionId} | User: %X{userId}] %msg%n

# 3. Log rotation limits
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30